JEIEvents.hideItems(event => {
  event.hide([
    'extendedcrafting:pedestal',
    'extendedcrafting:black_iron_block',
    'extendedcrafting:flux_star_block',
    'extendedcrafting:flux_star',
    'extendedcrafting:ender_star_block',
    'extendedcrafting:ender_star',
    'extendedcrafting:enhanced_ender_ingot',
    'extendedcrafting:enhanced_ender_ingot_block',
    'extendedcrafting:enhanced_ender_nugget',
    'extendedcrafting:enhanced_ender_catalyst',
    'extendedcrafting:enhanced_ender_component',
    'extendedcrafting:ender_ingot',
    'extendedcrafting:ender_ingot_block',
    'extendedcrafting:ender_component',
    'extendedcrafting:ender_catalyst',
    Item.of('ae2:facade', '{item:"extendedcrafting:ender_star_block"}'),
    Item.of('ae2:facade', '{item:"extendedcrafting:ender_ingot_block"}'),
    Item.of('ae2:facade', '{item:"extendedcrafting:redstone_ingot_block"}'),
    Item.of('ae2:facade', '{item:"extendedcrafting:enhanced_redstone_ingot_block"}'),
    Item.of('ae2:facade', '{item:"extendedcrafting:enhanced_ender_ingot_block"}'),
    Item.of('ae2:facade', '{item:"extendedcrafting:flux_star_block"}'),
    Item.of('ae2:facade', '{item:"extendedcrafting:black_iron_block"}'),
    'extendedcrafting:frame',
    'extendedcrafting:crafting_core',
    'extendedcrafting:ender_nugget',
    'extendedcrafting:black_iron_ingot',
    'extendedcrafting:black_iron_nugget',
    'extendedcrafting:black_iron_slate',
    'extendedcrafting:the_ultimate_block',
    'extendedcrafting:the_ultimate_ingot',
    'extendedcrafting:the_ultimate_component',
    'extendedcrafting:the_ultimate_catalyst',
    'extendedcrafting:redstone_catalyst',
    'extendedcrafting:enhanced_redstone_catalyst',
    'extendedcrafting:enhanced_redstone_component',
    'extendedcrafting:the_ultimate_nugget',
    'extendedcrafting:redstone_ingot',
    'extendedcrafting:redstone_nugget',
    'extendedcrafting:enhanced_redstone_ingot',
    'extendedcrafting:enhanced_redstone_nugget',
    'extendedcrafting:redstone_ingot_block',
    'extendedcrafting:enhanced_redstone_ingot_block',
    'extendedcrafting:crystaltine_catalyst',
    Item.of('patchouli:guide_book', '{"patchouli:book":"extendedcrafting:guide"}'),
    Item.of('extendedcrafting:recipe_maker', '{Shapeless:0b,Type:"Datapack"}'),
    Item.of('extendedcrafting:recipe_maker', '{Shapeless:0b,Type:"CraftTweaker"}'),
  ])
})
