ClientEvents.lang('en_us', event => {
  // Materials
  event.add('meatsalad', 'material.meatsalad.adamantite', 'Adamantite')
  event.add('meatsalad', 'material.meatsalad.aquamarine', 'Aquamarine')
  event.add('meatsalad', 'material.meatsalad.arcane_cloth', 'Arcane Cloth')
  event.add('meatsalad', 'material.meatsalad.awakened_adamantite', 'Awakened Adamantite')
  event.add('meatsalad', 'material.meatsalad.awakened_mythril', 'Awakened Mythril')
  event.add('meatsalad', 'material.meatsalad.awakened_palladium', 'Awakened Palladium')
  event.add('meatsalad', 'material.meatsalad.awakened_unobtainium', 'Awakened Unobtainium')
  event.add('meatsalad', 'material.meatsalad.awakened_vibranium', 'Awakened Vibranium')
  event.add('meatsalad', 'material.meatsalad.dragon_scale', 'Dragon Scale')
  event.add('meatsalad', 'material.meatsalad.echo', 'Echo')
  event.add('meatsalad', 'material.meatsalad.infinity', 'Infinity')
  event.add('meatsalad', 'material.meatsalad.jade', 'Jade')
  event.add('meatsalad', 'material.meatsalad.mythril', 'Mythril')
  event.add('meatsalad', 'material.meatsalad.allthemodium', 'Palladium')
  event.add('meatsalad', 'material.meatsalad.peridot', 'Peridot')
  event.add('meatsalad', 'material.meatsalad.ruby', 'Ruby')
  event.add('meatsalad', 'material.meatsalad.sapphire', 'Sapphire')
  event.add('meatsalad', 'material.meatsalad.topaz', 'Topaz')
  event.add('meatsalad', 'material.meatsalad.unobtainium', 'Unobtainium')
  event.add('meatsalad', 'material.meatsalad.vibranium', 'Vibranium')
  event.add('meatsalad', 'material.meatsalad.vulcanite', 'Vulcanite')

  // Gates
  event.add('meatsalad', 'meatsalad.basalz', 'Basalz Gateway')
  event.add('meatsalad', 'meatsalad.blitz', 'Blitz Gateway')
  event.add('meatsalad', 'meatsalad.blizz', 'Blizz Gateway')
  event.add('meatsalad', 'meatsalad.creeper', 'Creeper Gateway')
  event.add('meatsalad', 'meatsalad.magic', 'Magic Gateway')
  event.add('meatsalad', 'meatsalad.magma_cube', 'Magma Cube Gateway')
  event.add('meatsalad', 'meatsalad.otherside', 'Otherside Gateway')
  event.add('meatsalad', 'meatsalad.outer_end', 'Outer End Gateway')
  event.add('meatsalad', 'meatsalad.shulker', 'Shulker Gateway')
  event.add('meatsalad', 'meatsalad.skeleton', 'Skeleton Gateway')
  event.add('meatsalad', 'meatsalad.spider', 'Spider Gateway')
  event.add('meatsalad', 'meatsalad.stronghold', 'Stronghold Gateway')
  event.add('meatsalad', 'meatsalad.supreme', '§kSupreme§r Gateway')
  event.add('meatsalad', 'meatsalad.witch', 'Witch Gateway')
  event.add('meatsalad', 'meatsalad.wither_skeleton', 'Wither Skeleton Gateway')
  event.add('meatsalad', 'meatsalad.zombie', 'Zombie Gateway')
  event.add('meatsalad', 'name.gateways.corrupted_husk', 'Corrupted Husk')
  event.add('meatsalad', 'name.gateways.corrupted_vindicator', 'Corrupted Vindicator')
  event.add('meatsalad', 'name.gateways.corrupted_archevoker', 'Corrupted Archevoker')
  
  event.add('meatsalad', 'rewards.meatsalad.loot_table.stage_5_dungeon', 'Overworld Dungeon Loot')
  event.add('meatsalad', 'rewards.meatsalad.loot_table.stronghold', 'Stronghold Loot')
  event.add('meatsalad', 'rewards.meatsalad.loot_table.magic', 'Magic Loot')
  event.add('meatsalad', 'rewards.meatsalad.loot_table.otherside', 'The Other Loot')
  event.add('meatsalad', 'rewards.meatsalad.loot_table.outer_end', 'End Loot')
  event.add('meatsalad', 'rewards.meatsalad.loot_table.supreme', '§kSupreme§r Loot')

  // Extra Summon Entity Names
  event.add('meatsalad', 'name.meatsalad.ancient_remnant_1', 'Ancient Remnant+')
  event.add('meatsalad', 'name.meatsalad.ancient_remnant_2', 'Ancient Remnant++')
  event.add('meatsalad', 'name.meatsalad.ancient_remnant_3', 'Ancient Remnant+++')
  event.add('meatsalad', 'name.meatsalad.ender_guardian_1', 'Ender Guardian+')
  event.add('meatsalad', 'name.meatsalad.ender_guardian_2', 'Ender Guardian++')
  event.add('meatsalad', 'name.meatsalad.ender_guardian_3', 'Ender Guardian+++')
  event.add('meatsalad', 'name.meatsalad.ignis_1', 'Ignis+')
  event.add('meatsalad', 'name.meatsalad.ignis_2', 'Ignis++')
  event.add('meatsalad', 'name.meatsalad.ignis_3', 'Ignis+++')
  event.add('meatsalad', 'name.meatsalad.netherite_monstrosity_1', 'Netherite Monstrosity+')
  event.add('meatsalad', 'name.meatsalad.netherite_monstrosity_2', 'Netherite Monstrosity++')
  event.add('meatsalad', 'name.meatsalad.netherite_monstrosity_3', 'Netherite Monstrosity+++')
  event.add('meatsalad', 'name.meatsalad.the_harbinger_1', 'The Harbinger+')
  event.add('meatsalad', 'name.meatsalad.the_harbinger_2', 'The Harbinger++')
  event.add('meatsalad', 'name.meatsalad.the_harbinger_3', 'The Harbinger+++')

  // Infuse Types
  event.add('meatsalad', 'infuse_type.kubejs.dimensional_shard', "Dimensional Shard")

  // Slurries
  global.mekStackAdditions.forEach(entry => {
    event.add('meatsalad', `slurry.kubejs.clean_${entry.material}`, global.getReadableText(`clean_${entry.material}_slurry`))
    event.add('meatsalad', `slurry.kubejs.dirty_${entry.material}`, global.getReadableText(`dirty_${entry.material}_slurry`))
  })

  // Mob Effects
  event.add('meatsalad', 'effect.meatsalad.magic_forbiden', 'Magic Forbiden')
  event.add('meatsalad', 'effect.meatsalad.magic_forbiden.description', 'Disables magic')
  event.add('meatsalad', 'effect.meatsalad.glimpse_of_god', 'Divine Grace: Glimpse')
  event.add('meatsalad', 'effect.meatsalad.glimpse_of_god.description', 'Just a glimpose of the divine magic of a god. Capable of damage immunity')
  event.add('meatsalad', 'effect.meatsalad.gaze_of_god', 'Divine Grace: Gaze')
  event.add('meatsalad', 'effect.meatsalad.gaze_of_god.description', 'Start to feel the divine magic of a god. Capable of damage immunity')
  event.add('meatsalad', 'effect.meatsalad.glare_of_god', 'Divine Grace: Glare')
  event.add('meatsalad', 'effect.meatsalad.glare_of_god.description', 'Encounter the divine magic of a god. Capable of damage immunity')
  event.add('meatsalad', 'effect.meatsalad.pardon_of_god_magic', 'God\'s License: Magic Immunity')
  event.add('meatsalad', 'effect.meatsalad.pardon_of_god_magic.description', 'Grants magic damage immunity via the divine magic of a god')
  event.add('meatsalad', 'effect.meatsalad.pardon_of_god_melee', 'God\'s License: Melee Immunity')
  event.add('meatsalad', 'effect.meatsalad.pardon_of_god_melee.description', 'Grants melee damage immunity via the divine magic of a god')
  event.add('meatsalad', 'effect.meatsalad.pardon_of_god_projectile', 'God\'s License: Projectile Immunity')
  event.add('meatsalad', 'effect.meatsalad.pardon_of_god_projectile.description', 'Grants projectile damage immunity via the divine magic of a god')

  // Advancements
  event.add('meatsalad', 'advancements.meatsalad.the_nether.description', 'Transition into The Nether Stage')
  event.add('meatsalad', 'advancements.meatsalad.the_nether.title', 'The Nether Stage')
  event.add('meatsalad', 'advancements.meatsalad.hellshelf.description', 'Transition into The Hellshelf Stage')
  event.add('meatsalad', 'advancements.meatsalad.hellshelf.title', 'Hellshelf Stage')
  event.add('meatsalad', 'advancements.meatsalad.deepshelf.description', 'Transition into The Deepshelf Stage')
  event.add('meatsalad', 'advancements.meatsalad.deepshelf.title', 'Deepshelf Stage')
  event.add('meatsalad', 'advancements.meatsalad.the_other.description', 'Transition into The Other Stage')
  event.add('meatsalad', 'advancements.meatsalad.the_other.title', 'The Other Stage')
  event.add('meatsalad', 'advancements.meatsalad.the_end.description', 'Transition into The End Stage')
  event.add('meatsalad', 'advancements.meatsalad.the_end.title', 'The End Stage')
  event.add('meatsalad', 'advancements.meatsalad.endshelf.description', 'Transition into The Endshelf Stage')
  event.add('meatsalad', 'advancements.meatsalad.endshelf.title', 'Endshelf Stage')
})
