ServerEvents.recipes(event => {
  /*
  fullRemove('cataclysm:mechanical_fusion_anvil')
  */
  removeRecipes(event, [
    'cataclysm:abyssal_sacrifice',
    'cataclysm:abyssal_sacrifice2',
    'cataclysm:ancient_metal_block',
    'cataclysm:ancient_metal_ingot',
    'cataclysm:ancient_metal_ingot_from_nuggets',
    'cataclysm:bone_reptile_helmet',
    'cataclysm:bone_reptile_chestplate',
    'cataclysm:bulwark_of_the_flame',
    //'cataclysm:weapon_infusion/gauntlet_of_bulwark',
    'cataclysm:gauntlet_of_guard',
    'cataclysm:ignitium_block',
    'cataclysm:ignitium_ingot',
    'cataclysm:ignitium_upgrade_smithing_template',
    'cataclysm:laser_gatling',
    'cataclysm:the_incinerator',
    'cataclysm:meat_shredder',
    'cataclysm:smithing/ignitium_helmet',
    'cataclysm:smithing/ignitium_chestplate',
    'cataclysm:smithing/ignitium_elytra_chestplate',
    'cataclysm:smithing/ignitium_leggings',
    'cataclysm:smithing/ignitium_boots',
    'cataclysm:smithing/monstrous_helm',
    'cataclysm:sticky_gloves',
    //'cataclysm:weapon_infusion/void_assault_shoulder_weapon',
    //'cataclysm:weapon_infusion/void_forge',
    'cataclysm:witherite_ingot',
    'cataclysm:witherite_block',
    'cataclysm:wither_assault_shoulder_weapon',
  ])
})
