
#List of curio slot type settings
[[curiosSettings]]
	identifier = "head"
	size = 1
	override = true

[[curiosSettings]]
	identifier = "necklace"
	size = 1
	override = true

[[curiosSettings]]
	identifier = "back"
	size = 1
	override = true

[[curiosSettings]]
	identifier = "body"
	size = 1
	override = true

[[curiosSettings]]
	identifier = "feet"
	size = 1
	override = true

[[curiosSettings]]
	identifier = "hands"
	size = 1
	override = true

[[curiosSettings]]
	identifier = "belt"
	size = 1
	override = true

[[curiosSettings]]
	identifier = "bracelet"
	size = 1
	override = true

[[curiosSettings]]
	identifier = "ring"
	size = 1
	override = true

[[curiosSettings]]
	identifier = "charm"
	size = 2
	override = true
    
[[curiosSettings]]
	identifier = "angelring"
	size = 0
    visible = false
	override = true
