#List of slots to create or modify.
#See documentation for syntax: https://docs.illusivesoulworks.com/curios/configuration#slot-configuration
#
slots = ["id=grid;size=0", "id=heartamulet;size=0", "id=angelring;size=0", "id=ring;size=1", "id=bracelet;size=1", "id=head;size=0", "id=hands;size=0", "id=body;size=0", "id=feet;size=0", "id=charm;size=3"]

