
#General settings
[general]
	#Sets the range in blocks in which the structure compasses can locate structures [default: 10000]
	#Range: > 0
	compassRange = 10000
	#Defines if the structure compass should only locate unexplored structures. A structure is tagged as explored when the compass is used to find it. [default: false]]
	locateUnexplored = false
	#Defines if the structure compass should locate structures asynchronously [default: false]
	locateAsync = true
	#Defines which structures can't be searched with the Structure Compass
	#(Supports wildcard *, Example: 'minecraft:*' will blacklist anything in the minecraft domain)
	structureBlacklist = ["minecraft:desert_pyramid", "minecraft:fortress", "minecraft:jungle_pyramid", "minecraft:mineshaft", "minecraft:mineshaft_mesa", "minecraft:monument", "minecraft:pillager_outpost", "minecraft:stronghold", "minecraft:swamp_hut", "minecraft:village_desert", "minecraft:village_plains", "minecraft:village_savanna", "minecraft:village_snowy", "minecraft:village_taiga", "ctov:*", "mes:astral_hideaway", "mes:ender_spire", "mes:enderbloom_grove", "mes:enderkeep_courtyard", "mes:enderpin_spikes", "mes:enderskog", "mes:enderwatch_tower", "mes:endscraps", "mes:manuscript_shrine", "mes:monolith", "mes:mythic_garden", "mes:phantom_citadel", "mes:placid_prairie", "mes:ruined_pillar", "mes:starlight_voyager"]

