
[Ores]

	[Ores."End Neutronium"]
		#Number of veins per chunk that the ore spawns in
		#Range: 0 ~ 32
		count = 1
		#Size of veins
		#Range: 1 ~ 8
		size = 3
		#The chance (1 in N) of generating in any given chunk
		#Range: 1 ~ 16
		rarity = 3
		#Minimum Y-coordinate (base height) of veins
		#Range: 1 ~ 48
		minHeight = 8
		#Maximum Y-coordinate (highest level) of veins
		#Range: 24 ~ 128
		maxHeight = 24
		#The chance (out of 1) that the ore will not generate if exposed to air
		#Range: 0.0 ~ 1.0
		discardChanceOnAirExposure = 1.0

